steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cariuska-geral/nodeJS:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cariuska-geral/nodeJS:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [run', 'deploy', 'nodeJS', '--region=us-central1', '--platform=managed', '--image=gcr.io/cariuska-geral/nodeJS:$COMMIT_SHA']
  